schema-version: v2
kind: plugin
metadata:
  name: plugin-kotlin-spring-base-template
  display-name: plugin-kotlin-spring-base-template
  description: plugin inicial para aplicações kotlin e spring
  version: 1.0.2
  picture: plugin.png
spec:
  type: app
  compatibility:
    - kotlin
    - spring
    - maven
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  inputs:
    - label: Project name
      type: text
      name: project_name
      default: project-name
      global: true
      required: false
    - label: Group Id
      type: text
      name: project_group_id
      default: br.com.vitorino
      global: true
      required: false
    - label: Artifact Id
      type: text
      name: project_artifact_id
      global: true
      required: true
    - label: Version
      type: text
      name: version
      default: 1.0.0
      global: true
      required: false
    - label: Description
      type: text
      name: project_description
      default: Template Project using kotlin, maven and spring boot
      global: false
      required: false
    - label: Main Class
      type: text
      name: main_class
      default: Start
      global: true
      required: false
  global-computed-inputs:
    "application_name": "{{main_class|replace('-','')|replace('.','')|replace('/','')}}"
    "base_package": "{{project_group_id}}.{{project_artifact_id}}"
    "package_dir": "{{base_package|replace('.','/')}}"